# Generated by Django 6.0.2 on 2026-02-21 18:43

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('cost_price', models.DecimalField(max_digits=10, decimal_places=2)),
                ('selling_price', models.DecimalField(max_digits=10, decimal_places=2)),
                ('minimum_stock', models.IntegerField(default=0)),
                ('current_stock', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_produced', models.IntegerField()),
                ('production_date', models.DateField(default=timezone.now)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='productions', to='core.product')),
                ('produced_by', models.ForeignKey(null=True, on_delete=models.deletion.SET_NULL, related_name='productions', to='accounts.user')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('customer_name', models.CharField(max_length=200)),
                ('total_amount', models.DecimalField(max_digits=10, decimal_places=2, default=0)),
                ('sale_date', models.DateField(default=timezone.now)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sold_by', models.ForeignKey(null=True, on_delete=models.deletion.SET_NULL, related_name='sales', to='accounts.user')),
            ],
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_sold', models.IntegerField()),
                ('unit_price', models.DecimalField(max_digits=10, decimal_places=2)),
                ('discount', models.DecimalField(max_digits=5, decimal_places=2, default=0)),
                ('product', models.ForeignKey(null=True, on_delete=models.deletion.SET_NULL, related_name='sale_items', to='core.product')),
                ('sale', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='items', to='core.sale')),
            ],
        ),
        migrations.CreateModel(
            name='StockHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(max_length=20)),
                ('quantity_change', models.IntegerField()),
                ('previous_quantity', models.IntegerField()),
                ('new_quantity', models.IntegerField()),
                ('reference_id', models.CharField(max_length=100, blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=models.deletion.SET_NULL, related_name='stock_changes', to='accounts.user')),
                ('product', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='stock_history', to='core.product')),
            ],
        ),
    ]
